[workspace]
channels = ["conda-forge"]
name = "Test-SlaterGPU-as-dependency"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
SlaterGPU = { git = "https://github.com/ZimmermanGroup/SlaterGPU.git" }
